### ISSUE TITLE
Create applicant/application model & endpoint

### ISSUE THREAD

**Issue by freeatnet** [uoft-tapp/old-orig-tapp#12]
- [x] Create the model
- [x] Create an endpoint to list applicants/applications
- [x] Provide RSpec tests for all code

**Comment by simpslandyy** [comment]
I can take on this issue :)

**Comment by simpslandyy** [comment]
@freeatnet - after this meta has been completed do we close it or move it to completed ... or does it stay here?

**Comment by freeatnet** [comment]
@simpslandyy I'd suggest "close & leave in meta column". How's that sound?
