### ISSUE TITLE
no progress feedback while uploading chass import file

### ISSUE THREAD

**Issue by jmzaleski** [uoft-tapp/old-orig-tapp#147]

**Comment by gabriellesc** [comment]
Is this in CP or TAPP?
Edit: @michellemtchai says this refers to TAPP

**Comment by gabriellesc** [comment]
~Should be resolved by #182~
#182 needed to be refactored on top of #181.
I instead attempted to create a new branch off `development` and recreate #181 in that branch.
However, I accidentally made these changes directly in `development`, in f1df6b8

This issue should now be resolved in `development`.

**Comment by jmzaleski** [comment]
I see a pink box in master, but in development not.

**Comment by gabriellesc** [comment]
@jmzaleski I'm not sure what you're referring to?
The only change brought about by #182 (now in `development` - see comment above) should have a spinner instead of the import button, while an import to CHASS is in progress.
