### ISSUE TITLE
don't know how to restore from pg_dumpall of databases

### ISSUE THREAD

**Issue by jmzaleski** [uoft-tapp/old-orig-tapp#148]
by way of coming up with a backup/restore recipe..

With a running system, execute:

`
docker exec -it tapp_postgress_1 pg_dumpall -U tapp > /tmp/pg_dumpall-aug4-1400.sql
`
Now shut down system and blow away database (-v eliminates all volumes from all containers, which at the moment blows away the postgress volume)

`docker-compose down -v
`
Now, fire up system again, with no database:
`docker-compose up
`
Copy pg_dump into postgress container:
`docker cp  /tmp/pg_dumpall.sql  tapp_postgres_1:/tmp
`
Now ssh into postgress container:
`docker exec -it tapp_postgres_1 bash
`
su to postgress user (i'm guessing at this point)
# su - postgres

and restore the db
`psql < /tmp/pg_dumpall.sql
`
shut down everything (`docker-compose down` ###NO -v!!!
start up everything: `docker-compose up`

when visit http://tapp.cs.toronto.edu/index.html now see on console:
```
rails-app_1  | Use Ctrl-C to stop
postgres_1   | ERROR:  relation "assignments" does not exist at character 29
postgres_1   | STATEMENT:  SELECT "assignments".* FROM "assignments"
postgres_1   | ERROR:  relation "applications" does not exist at character 30
postgres_1   | STATEMENT:  SELECT "applications".* FROM "applications"
postgres_1   | ERROR:  relation "positions" does not exist at character 27
postgres_1   | STATEMENT:  SELECT "positions".* FROM "positions"
postgres_1   | ERROR:  relation "applicants" does not exist at character 28
postgres_1   | STATEMENT:  SELECT "applicants".* FROM "applicants"
postgres_1   | ERROR:  relation "instructors" does not exist at character 29
postgres_1   | STATEMENT:  SELECT "instructors".* FROM "instructors"
```
what is wrong with this recipe??

Finally, a link to the output of pg_dumpall. To my untrained eye it appears to have everything, including one assignment:

```
COPY assignments (id, applicant_id, position_id, export_date, created_at, updated_at, hours) FROM stdin;
1	199	1	\N	2017-08-09 19:09:16.906444	2017-08-09 19:09:16.906444	14
\.
```
[pg_dumpall-aug9-1510-one-assignee.sql](https://u89646020.dl.dropboxusercontent.com/u/89646020/pg_dumpall-aug9-1510-one-assignee.sql)

**Comment by jmzaleski** [comment]
ah, check out [](https://www.postgresql.org/docs/9.1/static/backup.html)

it suggests that I could have used pgdump db-name instead of pg_dumpall.

**Comment by freeatnet** [comment]
The first command in this issue doesn't make sense or work for me, was there a bad copy-paste somewhere?

**Comment by freeatnet** [comment]
FWIW, two things may make this easier:
1. Using `docker-compose exec postgres` in place of `docker exec -it tapp_postgres_1` — docker-compose will automatically find the right fully qualified container name.
2. Using stdin/out instead of copying files, eg., `pg_dumpall -U tapp > /path/to/host/backup/dir/backup.sql` `psql -f - < /path/to/host/backup/dir/backup.sql` : saves a few commands, removes a few places where things may go wrong

**Comment by freeatnet** [comment]
Here's what I tried:
```

$ docker-compose exec postgres pg_dumpall -U tapp > tmp/postgres-backup.sql
[success, I have a file that seems to contain all the data]
$ docker-compose down -v; docker-compose up # in another bash session
$ docker-compose exec postgres psql -U tapp tapp_development -f - <  tmp/postgres-backup.sql
[a bunch of stuff echoed back]
```

In the postgres log, I saw the following errors that seem to indicate psql had trouble reading the output of `pg_dumpall`:
```
postgres_1            | ERROR:  invalid input syntax for integer: ""
postgres_1            | CONTEXT:  COPY applicants, line 1, column id: ""
postgres_1            | STATEMENT:  COPY applicants (id, utorid, app_id, student_number, first_name, last_name, email, phone, address, commentary, created_at, updated_at, dept, yip, program_id) FROM stdin;
postgres_1            | ERROR:  invalid input syntax for integer: ""
postgres_1            | CONTEXT:  COPY applications, line 1, column id: ""
postgres_1            | STATEMENT:  COPY applications (id, applicant_id, ta_training, access_acad_history, ta_experience, academic_qualifications, technical_skills, availability, other_info, special_needs, raw_prefs, created_at, updated_at, round_id) FROM stdin;
postgres_1            | ERROR:  missing data for column "value"
postgres_1            | CONTEXT:  COPY ar_internal_metadata, line 1: ""
postgres_1            | STATEMENT:  COPY ar_internal_metadata (key, value, created_at, updated_at) FROM stdin;
postgres_1            | ERROR:  invalid input syntax for integer: ""
postgres_1            | CONTEXT:  COPY assignments, line 1, column id: ""
postgres_1            | STATEMENT:  COPY assignments (id, applicant_id, position_id, export_date, created_at, updated_at, hours) FROM stdin;
postgres_1            | ERROR:  invalid input syntax for integer: ""
postgres_1            | CONTEXT:  COPY campus, line 1, column code: ""
postgres_1            | STATEMENT:  COPY campus (code, name) FROM stdin;
postgres_1            | ERROR:  invalid input syntax for integer: ""
postgres_1            | CONTEXT:  COPY instructors, line 1, column id: ""
postgres_1            | STATEMENT:  COPY instructors (id, name, email, utorid, created_at, updated_at) FROM stdin;
postgres_1            | ERROR:  invalid input syntax for integer: ""
postgres_1            | CONTEXT:  COPY instructors_positions, line 1, column instructor_id: ""
postgres_1            | STATEMENT:  COPY instructors_positions (instructor_id, position_id) FROM stdin;
postgres_1            | ERROR:  invalid input syntax for integer: ""
postgres_1            | CONTEXT:  COPY positions, line 1, column id: ""
postgres_1            | STATEMENT:  COPY positions (id, "position", round_id, open, campus_code, course_name, estimated_enrolment, duties, qualifications, hours, estimated_count, estimated_total_hours, created_at, updated_at, session_id) FROM stdin;
```

**Comment by lloyd-uot-cs** [comment]
On 8/9/2017 5:37 PM, Mathew Zaleski wrote:
>
> ah, check out
>
> it suggests that I could have used pgdump db-name instead of pg_dumpall.
>

`pg_dumpall` is good in "normal" circumstances because it requires zero 
knowledge(*)
of the database, but our difficulties suggest maybe we should try 
pgdump, keeping
in mind that if/when more databases (eg. cp_production) start showing up 
this will
need to be revisited.

regards,
lloyd

(* zero knowledge is the kind I'm best at :-)

**Comment by reidka** [comment]
@freeatnet I think the error you are seeing is more about stdin/stdout problems between docker and the host.  I don't see that sort of problem when I copy the file to the container.

I thought I had it working before, but I'm now having trouble getting the database into the right state to accept the restore.  It needs to be created but not populated.

**Comment by jmzaleski** [comment]
sorry all, i copy/pasted the wrong command up there. It was supposed to be:

`docker exec -it tapp_postgress_1 pg_dumpall -U tapp > /tmp/pg_dumpall-aug4-1400.sql
`

**Comment by jmzaleski** [comment]
specific dump command:

`pg_dump tapp_production --verbose --username=postgres 
`

**Comment by reidka** [comment]
I'll have to repeat this one more time to confirm, but I think the following worked (Almost certainly some parts are unnecessary.)

In one shell:
```
docker exec -it tapp_postgres_1 pg_dump -U tapp > dump.sql
docker-compose down -v
docker-compose up
docker-compose down
docker-compose run rails-app rake db:migrate db:seed
docker-compose run rails-app rake db:drop db:create
docker-compose up

```

In another shell:

```
docker cp dump.sql tapp_postgres_1:/tmp
docker exec -it tapp_postgres_1 bash
# on the container
psql -U tapp tapp_development < /tmp/dump.sql 
```

**Comment by jmzaleski** [comment]
specific restore command:
psql --username=postgres --variable=ON_ERROR_STOP=1 tapp_production < /tmp/xxx.sql

**Comment by jmzaleski** [comment]
Landy found the recipe:

```
docker-compose down
docker-compose up
docker-compose run rails-app rake db:drop
cat ../pg_dumps/pg_dumpall-aug9-1510-one-assignee.sql | docker exec -i tapp_postgres_1 psql -U postgres
```
this seems to do exactly what we want. Assignments come back.

**Comment by lloyd-uot-cs** [comment]
On 8/10/2017 1:13 PM, Mathew Zaleski wrote:
>
> Landy found the recipe:
>
> |docker-compose down docker-compose up docker-compose run rails-app 
> rake db:drop cat ../pg_dumps/pg_dumpall-aug9-1510-one-assignee.sql | 
> docker exec -i tapp_postgres_1 psql -U postgres |
>
> this seems to do exactly what we want. Assignments come back.
>

Awesome.

up down run rake drop cat

...sounds like the Alcatraz triathlon "Dig Run Swim" motto.

:-)

**Comment by simpslandyy** [comment]
Okay, so I think @jmzaleski and I figure this out, it still complains
`ERROR: role "postgres" already exists & role "tapp" already exists`
**but** it restores the data which is the goal! :)

Here's the recipe! :+1: 
-----------------
Back up using pgdump_all
`docker exec -t tapp_postgres_1 pg_dumpall -U postgres > filename` 

Stop and remove all running containers & volumes (you can actually remove individual containers as well. If that's of value to anyone I will post what I have up)
` docker-compose down -v`

Start up docker again
`docker-compose up`

Drop the database (so it doesn't complain that the db already exists when you do the dump)
`docker-compose run rails-app rake db:drop`

Then 
`cat filename | docker exec -i tapp_postgres_1 psql -U postgres`

**Comment by lloyd-uot-cs** [comment]
On 8/10/2017 2:03 PM, Landy Simpson wrote:
>
> Okay, so I think @jmzaleski <https://github.com/jmzaleski> and I 
> figure this out, it still complains
> |ERROR: role "postgres" already exists & role "tapp" already exists|
> *but* it restores the data which is the goal! :)
>

I've verified this works by restoring doc.cs from a dump from tapp.cs

I set up a cron job on tapp.cs running the dump command hourly.

We could run it more often, if you think things change too much in an hour.


lloyd

**Comment by jmzaleski** [comment]
done like dinner, as usual thanks to landy's research
