### ISSUE TITLE
Need clarification for CHASS courses JSON

### ISSUE THREAD

**Issue by michellemtchai** [uoft-tapp/old-orig-tapp#20]
- What is the difference between "hours" and "n_hours"? 
- What does "tutorial" entail? 
- Are "start_posting" and "end_posting" referring to the rounds or the semester?
- Is "end_nomination" referring to the end date for instructor to nominate students?
- What is the "status" referring to? 
- What is the "dates" referring to?
- Can you give us a standard format for dates?
- Is the "course_id" unique within a round?
- If the course was open in multiple rounds, would we get multiple entries of them?

Here are the parts I understand so far:
- "course_id": is a String with the pattern of [department_code][course_code][course_length(H/Y)][campus_code][section(F/S/Y)]
- "course_name": is a String that is the course name
- "round_id": is a String that identifies the round
- "enrollment": is a number that totals the students enrolled in the course
- "n_positions": is a number for the capacity of the offer in this course
- "n_hours": is a number
- "dates": is a String formatted as a date
- "tutorials": is a String
- "qualifications": is a String that describes the qualification for the course
- "duties": is a String that describes the duties of the TA for the course
- "total_hours": is a number
- "start_posting": is a String formatted as a date
- "end_posting": is a String formatted as a date
- "status": is a String
- "end_nominations": is a String formatted as a date
- "last_updated": is a String formatted as a date-time

**Comment by alynch** [comment]
Most of that information relates to the posting, and i don't think it's relevant for your work assigning positions. Probably the only relevant fields are total_hours (the number of TAship hours available for the course) and perhaps n_positions (the number of expected TA positions for the course).

**Comment by alynch** [comment]
n_hours is a string that departments use to indicate, roughly how many hours there are available (e.g., '70 hours per TA'). 
total_hours is an integer with the actual number of hours available.
course_id is unique within a round for the list of courses.
the JSON file is the extract for a given round

**Comment by michellemtchai** [comment]
Thank you for the clarification. I think I understand now. Thanks, again.
