### ISSUE TITLE
No way to associate courses and applicants in CHASS JSON

### ISSUE THREAD

**Issue by michellemtchai** [uoft-tapp/old-orig-tapp#21]
I noticed that while the applicant data contained profile information for the applicant, it didn't show which courses the applicants were applying for.

**Comment by michellemtchai** [comment]
@alynch Could you please clarify?

**Comment by alynch** [comment]
That was my oversight; the new version of the JSON file has an array with the list of courses the applicant selected.

**Comment by michellemtchai** [comment]
Thank you very much for updating the file.
