### ISSUE TITLE
Create Course and TA Position models & endpoints

### ISSUE THREAD

**Issue by freeatnet** [uoft-tapp/old-orig-tapp#23]
- [x] Verify what data is needed for Courses, TA Positions
- [x] Create models for Course and TA Position #25 
- [x] Allow course and position information to be imported #29 
- [x] Allow courses and positions to be listed
- [x] Allow course details and available positions to be retrieved by course code
- [x] Add RSpec tests to verify endpoint returns expected results and keys/values

**Comment by michellemtchai** [comment]
Course
  dept_code:string, NOT NULL
  course_code:string, NOT NULL
  course_type:string,
  campus_code:number,
  course_name:text,
  session_code:string,
  PRIMARY KEY(dept_code, course_code)

Instructor
  id:number, NOT NULL PRIMARY KEY
  name:string,
  is_coordinator:boolean,

TaughtBy
  dept_code:string, NOT NULL
  course_code:string, NOT NULL
  instructor:number, NOT NULL
  PRIMARY KEY(dept_code, course_code, instructor)

Position
  pid:number, NOT NULL PRIMARY KEY
  title:text,
  duties:text,
  qualifications:text,
  hours:text,
  capacity:number,

PositionFrom
  dept_code:string, NOT NULL
  course_code:string, NOT NULL
  pid:number, NOT NULL
  PRIMARY KEY (dept_code, course_code, pid)

**Comment by michellemtchai** [comment]
This is the revision made with @freeatnet 

```
Course
  course_code:string NOT NULL PRIMARY KEY # Like "CSC108H1F", "CSC108H5S"
  campus:references, # belongs_to :campus
  instructor:references, # belongs_to :instructor
  course_name:text
  estimated_enrolment:integer

Campus # Pre-set collection of campuses
  code:number NOT NULL PRIMARY KEY, # 1, 3, or 5
  name:string # "St George", "Scarborough", or "Mississauga"

Instructor
  name:string
  email:string

Position
  # there's a default 'id' PK here
  course:references # belongs_to :course -- has a one-to-many relationship with Course
  title:text
  # properties describing duties:
  duties:text
  qualifications:text
  hours:text # Number of hours -- per hire -- that this position requires
  # properties describing overall position:
  estimated_count:number # Estimated number of hires to be made for this position
  estimated_total_hours:numbers # Total number of work hours under this position
```

**Comment by gabriellesc** [comment]
Do we need a semester/session associated with a course and/or position?

**Comment by freeatnet** [comment]
Added "Add RSpec" checklist item
