### ISSUE TITLE
Clarification about some fields in the applicant data in CHASS JSON

### ISSUE THREAD

**Issue by simpslandyy** [uoft-tapp/old-orig-tapp#26]
What kind of data comes in deferral_status, deferral_reason?
(sorry if that's a little vague, but both fields come in as null so I'm wondering what I should be expecting in these fields ... specifically deferral_status)

**Comment by alynch** [comment]
Those two fields are used for subsequent appointments, so can ignore them (TAs can request to defer their entitlements, in which case they will not show up in the list of applicants for the round).

**Comment by michellemtchai** [comment]
I noticed that:
- no "status" for the student (for example: "undergrad", "grad", "PhD", "PostDoc", etc) 
- no "preference" text to order of courses the applicant wants

Also, is "degrees" the department the student is a part of? Is it a text box or a dropdown? Or is it something else? What is a "deferral_status"? Is it a String or number?

For now, this is what I understand from the JSON:
- app_id: is a String that contains only number and is unique to the applicant
- utorid: is a String that contains the applicant's utorid
- first_name: is a String that contains the applicant's first name
- last_name: is a String that contains the applicant's last name
- email: is a String that contains the applicant's email
- phone: is a String that contains the applicant's phone number and is style in the format "XXX-XXX-XXXX"
- student_no: is a String of numbers that represents the applicant's student number
- address: is a String that contains the address of the applicant
- ta_experience: is a String from a text box. It's presumed to be formatted for parsing.
- research: is a String from a text box. It's presumed to be unformatted.
- comments: is a String from a text box. It's a comment from the applicant(?)
- availability: is a String from a text box about times available. It's presumed to be unformatted(?)
- degrees: is a String 
- work_experience: is a String from a text box. It's presumed to be unformatted.
- hours_owed: is a number/integer
- pref_session: is a String with a choice of (Y/S/F)
- pref_campus: is a String of the campus name (St. George/Mississauga/Scarbourough)
- deferral_status: don't know
- deferral_reason: is a String and it is unformatted.
- appointment_no: is a number/integer
- courses: is an array of Strings with "course_id" from the courses JSON

**Comment by alynch** [comment]
`program_id` indicates the applicant's program (MSc, PhD, etc.). It's a foreign key to a 'programs' table that has the string representation of the program name.

Applicants can't currently rank the courses; they can only indicate which courses they would prefer to TA.

There is a `dept` field that indicates the department the student is enrolled in.

`degrees` is a custom field used by some departments that list all the degrees (and details) the student has. It is a text field, presented to the applicants as a textarea.

**Comment by michellemtchai** [comment]
Thank you very much for the explanation.
