### ISSUE TITLE
NoMethodError when using strong parameters' permit in a model

### ISSUE THREAD

**Issue by michellemtchai** [uoft-tapp/old-orig-tapp#35]
1. The commit where the error occurs is in PR#34. It is the latest commit in that PR.
2. In order to get to the error:
  * Run Docker, then Postman 
  * go to `PATCH /courses/csc108h1s`
3. The console should show:
`NoMethodError (undefined method 'permit' for #<Course:0x0055c4dd144d88>):`

Expected Result:
`estimated_enrolment` in Course is not present, so no update.

**Comment by freeatnet** [comment]
@michellemtchai I don't think I see any `permit` uses in #34 at the moment.

**Comment by freeatnet** [comment]
Line 10 of CoursesController does the following:
```
    params[:course] = course
```
which is then used in 
```
  def course_params
    params.require(:course).permit(:estimated_enrolment)
  end
```

Could you explain what you are attempting to accomplish there?

**Comment by michellemtchai** [comment]
I was trying to set the parameter the Course object. I guess I didn't need to do that... It worked after I removed the `:course` part. Thanks for the hint. :)
